#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd, using the while loop 

while IFS=: read -r username password uid gid fullname home shell; do
    # Output the formatted string
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $fullname."
    echo "-------------------------"
done < /etc/passwd
