#!/usr/bin/env bash
#this script prints "best school" unless it's the 4th line or 8th line where it prints "bad luck" & "good luck" respectfully
counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done

