#!/usr/env/bin bash
#script that displays the time for 12 hours and 59 minutes 

hour=0

# Loop through hours from 0 to 12
while [ $hour -le 12 ]; do
    minute=1
    # Loop through minutes from 1 to 59
    while [ $minute -le 59 ]; do
        echo "$hour:$minute"
        ((minute++))
    done
    ((hour++))
done

