#!/usr/bin/env bash
#script that stops 4-to_infinity_and_beyond process.
# Find the PID of the process containing "to_infinity_and_beyond"
pid=$(pgrep -f "to_infinity_and_beyond")

# Check if the process is found
if [[ -n "$pid" ]]; then
    kill "$pid"
    echo "Process with PID $pid has been terminated."
else
    echo "No process found with the name 'to_infinity_and_beyond'."
fi

