#!/usr/bin/env bash
#script that displays to infinity and beyond indefinitely
# Function to handle SIGTERM
handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}

# Trap SIGTERM signal
trap 'handle_sigterm' SIGTERM

# Loop indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 2
done

