#!/usr/bin/env bash
#Write a Bash script that kills the process 7-highlander.
# Find the PID of the process
#!/bin/bash

# Find the PID of the process
PID=$(pgrep "7-highlander")

# Check if the process is running
if [ -z "$PID" ]; then
  echo "OK"
else
  # Kill the process
  kill "$PID"
  echo "OK"
fi

